# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/umarn/workspace/brazilgame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/umarn/workspace/brazilgame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/umarn/workspace/brazilgame/CMakeFiles /Users/umarn/workspace/brazilgame//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/umarn/workspace/brazilgame/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named calclib

# Build rule for target.
calclib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calclib
.PHONY : calclib

# fast build rule for target.
calclib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/build
.PHONY : calclib/fast

#=============================================================================
# Target rules for targets named out

# Build rule for target.
out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 out
.PHONY : out

# fast build rule for target.
out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/build
.PHONY : out/fast

lib/glad.o: lib/glad.cpp.o
.PHONY : lib/glad.o

# target to build an object file
lib/glad.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/lib/glad.cpp.o
.PHONY : lib/glad.cpp.o

lib/glad.i: lib/glad.cpp.i
.PHONY : lib/glad.i

# target to preprocess a source file
lib/glad.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/lib/glad.cpp.i
.PHONY : lib/glad.cpp.i

lib/glad.s: lib/glad.cpp.s
.PHONY : lib/glad.s

# target to generate assembly for a file
lib/glad.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/lib/glad.cpp.s
.PHONY : lib/glad.cpp.s

src/ai.o: src/ai.cpp.o
.PHONY : src/ai.o

# target to build an object file
src/ai.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/ai.cpp.o
.PHONY : src/ai.cpp.o

src/ai.i: src/ai.cpp.i
.PHONY : src/ai.i

# target to preprocess a source file
src/ai.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/ai.cpp.i
.PHONY : src/ai.cpp.i

src/ai.s: src/ai.cpp.s
.PHONY : src/ai.s

# target to generate assembly for a file
src/ai.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/ai.cpp.s
.PHONY : src/ai.cpp.s

src/draw.o: src/draw.cpp.o
.PHONY : src/draw.o

# target to build an object file
src/draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/draw.cpp.o
.PHONY : src/draw.cpp.o

src/draw.i: src/draw.cpp.i
.PHONY : src/draw.i

# target to preprocess a source file
src/draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/draw.cpp.i
.PHONY : src/draw.cpp.i

src/draw.s: src/draw.cpp.s
.PHONY : src/draw.s

# target to generate assembly for a file
src/draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/draw.cpp.s
.PHONY : src/draw.cpp.s

src/editor.o: src/editor.cpp.o
.PHONY : src/editor.o

# target to build an object file
src/editor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/editor.cpp.o
.PHONY : src/editor.cpp.o

src/editor.i: src/editor.cpp.i
.PHONY : src/editor.i

# target to preprocess a source file
src/editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/editor.cpp.i
.PHONY : src/editor.cpp.i

src/editor.s: src/editor.cpp.s
.PHONY : src/editor.s

# target to generate assembly for a file
src/editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/editor.cpp.s
.PHONY : src/editor.cpp.s

src/input.o: src/input.cpp.o
.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i
.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s
.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/level.o: src/level.cpp.o
.PHONY : src/level.o

# target to build an object file
src/level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/level.cpp.o
.PHONY : src/level.cpp.o

src/level.i: src/level.cpp.i
.PHONY : src/level.i

# target to preprocess a source file
src/level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/level.cpp.i
.PHONY : src/level.cpp.i

src/level.s: src/level.cpp.s
.PHONY : src/level.s

# target to generate assembly for a file
src/level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/level.cpp.s
.PHONY : src/level.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/render.o: src/render.cpp.o
.PHONY : src/render.o

# target to build an object file
src/render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/render.cpp.o
.PHONY : src/render.cpp.o

src/render.i: src/render.cpp.i
.PHONY : src/render.i

# target to preprocess a source file
src/render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/render.cpp.i
.PHONY : src/render.cpp.i

src/render.s: src/render.cpp.s
.PHONY : src/render.s

# target to generate assembly for a file
src/render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/render.cpp.s
.PHONY : src/render.cpp.s

src/settings.o: src/settings.cpp.o
.PHONY : src/settings.o

# target to build an object file
src/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/settings.cpp.o
.PHONY : src/settings.cpp.o

src/settings.i: src/settings.cpp.i
.PHONY : src/settings.i

# target to preprocess a source file
src/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/settings.cpp.i
.PHONY : src/settings.cpp.i

src/settings.s: src/settings.cpp.s
.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/settings.cpp.s
.PHONY : src/settings.cpp.s

src/window.o: src/window.cpp.o
.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i
.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s
.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

src/world.o: src/world.cpp.o
.PHONY : src/world.o

# target to build an object file
src/world.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/world.cpp.o
.PHONY : src/world.cpp.o

src/world.i: src/world.cpp.i
.PHONY : src/world.i

# target to preprocess a source file
src/world.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/world.cpp.i
.PHONY : src/world.cpp.i

src/world.s: src/world.cpp.s
.PHONY : src/world.s

# target to generate assembly for a file
src/world.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calclib.dir/build.make CMakeFiles/calclib.dir/src/world.cpp.s
.PHONY : src/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... calclib"
	@echo "... out"
	@echo "... lib/glad.o"
	@echo "... lib/glad.i"
	@echo "... lib/glad.s"
	@echo "... src/ai.o"
	@echo "... src/ai.i"
	@echo "... src/ai.s"
	@echo "... src/draw.o"
	@echo "... src/draw.i"
	@echo "... src/draw.s"
	@echo "... src/editor.o"
	@echo "... src/editor.i"
	@echo "... src/editor.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/level.o"
	@echo "... src/level.i"
	@echo "... src/level.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/render.o"
	@echo "... src/render.i"
	@echo "... src/render.s"
	@echo "... src/settings.o"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

